### ISSUE TITLE
Cannot Resolve Package ‘Graph’

### ISSUE THREAD

**Issue by nolochemical** [apple/swift-markdown#101]
**Swift playground app(on iPad)**

Could not resolve package graph. Cannot continue.

[DependencyResolver] derived 'swift-markdown' requirement '0.1.0..<1.0.0'

[DependencyResolver] resolving 'swift-markdown'

Could not find branch: 'gfm' in https://github.com/apple/swift-markdown

**Comment by transat** [comment]
I'm having the same issue trying to use this package in Swift Playgrounds:

Could not resolve package graph. Cannot continue.
Dependencies could not be resolved because root depends on 'swift-markdown' 0.1.0..<1.0.0.
'swift-markdown' >= 0.1.0 cannot be used because no versions of 'swift-markdown' match the requirement 0.1.1.. <1.0.0 and package 'swift-markdown' is required using a stable-version but
'swift-markdown' depends on an unstable-version package 'swift-cmark'

**Comment by Kyle-Ye** [comment]
Yes, swift-markdown have a branch dependency on swift-cmark:gfm.

Since we are releasing versioned release of swift-markdown, can we also release a version for swift-cmark, update swift-markdown's dependency to cmark from branch "gfm" to version "xx" in "swift-markdown-0.2" branch and release a new version to fix this?

I can do the step 2. But I do not have the relevant permission to release a new version in swift-cmark. cc @QuietMisdreavus

**Comment by QuietMisdreavus** [comment]
Swift-Markdown's `0.2.0` tag was already using a tag requirement for swift-cmark; the issue mainly comes in when you're also using a branch requirement for Swift-Markdown itself, since development versions also use a branch requirement.

Regardless, today i tagged [`0.3.0`](https://github.com/apple/swift-markdown/releases/tag/0.3.0), based on the Swift 5.9 release.

**Comment by Kyle-Ye** [comment]
The original version issue is fixed when 0.2 release is created. And you can choose 0.2 or 0.3 now.

However you still can't use this package on Swift Playground because it contains a Clang target. This is an expected behavior and you can file a feedback to Apple.
