### ISSUE TITLE
Can not preview with SwiftUI

### ISSUE THREAD

**Issue by chocoford** [apple/swift-markdown#121]
Platform: macOS 13.3 (22E252)

Xcode version: Version 14.3 (14E222b)

Error description: `missing required modules: 'CAtomic', 'cmark_gfm', 'cmark_gfm_extensions'`
```
SwiftEmitModule normal arm64 Emitting\ module\ for\ ... (in target '...' from project '...')
```

**Comment by Kyle-Ye** [comment]
Generally speaking, `Xcode Preview` and `SwiftUI` related issues should be reported to Apple via their bug system or [Apple Developer Forum](https://developer.apple.com/forums/)

And for your issue, I have no problem previewing with swift-markdown. And I suspect it was due to the incomplete package resolution. Make sure you see a success on Xcode's package resolve and added the package to your target.

If you still see such issue, maybe you can provide a minimal reproductive project so that I can help confirm and identity your issue. 

Finally you can have a look at some other great community maintained SwiftUI + swift-markdown library. (eg. https://github.com/LiYanan2004/MarkdownView) They all build and preview with Xcode fine.

Feel free to reopen the issue if you have further info to provide.

**Comment by dfeinzimer** [comment]
@chocoford Did you ever find a resolution for this? I'm hitting the same error, but only when I have another dependency in my Swift Package. When `swift-markdown` is my only dependency, previews work just fine.
