### ISSUE TITLE
improve efficiency of Aside.Kind.init(rawValue:)?

### ISSUE THREAD

**Issue by kelvin13** [apple/swift-markdown#48]
can this be implemented a little more efficiently?

https://github.com/apple/swift-markdown/blob/97df6e2812adcf8698204ca5f0756563ef36e5c1/Sources/Markdown/Interpretive%20Nodes/Aside.swift#L95

**Comment by d-ronnqvist** [comment]
I'm not sure why this issue is phrased as a question and if the issue description is pointing out a performance problem or asking if the code could cause a performance problem. 

Quickly looking at the code; `casesAndLowercasedRawValues` could be precomputed once and the lowercased raw value could be computed outside of the `first(where:)` closure. That said, the number of cases is fairly small (~20) and this initializer would only be called once per authored aside in the content. Even for large amounts of content with many asides I'm not sure if either of those changes would result in any measurable improvements overall.

If you want to work on this I can help with some input on how to gather measurements.

**Comment by Kyle-Ye** [comment]
Maybe we can simply use String.caseInsensitiveCompare to improve this.
```swift
public init?(rawValue: String) {
    guard let kind = Kind.allCases.first(where: { $0.rawValue.caseInsensitiveCompare(rawValue) == .orderedSame }) else {
        return nil
    }
    self = kind
}
```

**Comment by Kyle-Ye** [comment]
Close #48 and #55 due to the change of #60
