### ISSUE TITLE
Fatal error: Unknown cmark node type 'attribute'

### ISSUE THREAD

**Issue by gfinger** [apple/swift-markdown#90]
Initializing a Document with a string containing custom attributes like 
`^[bla](xyz: 'abc')` 
brings` up a fatal error: 
`Markdown/CommonMarkConverter.swift:139: Fatal error: Unknown cmark node type 'attribute' encountered during conversion`.
Entering any text as input for a Document must never end up in a fatal error. The Document is often directly initialised from a user input, which must never stop the execution of the program. A simple fix would just ignore all unknown node types.

**Comment by QuietMisdreavus** [comment]
This specific issue should be fixed by https://github.com/apple/swift-markdown/pull/25.

I do agree that it's worth not crashing over unknown elements from cmark. However, it's still worth knowing when something is wrong rather than just dropping things silently. I wonder if it would be worth adding a debug assertion instead of a fatal error? That way release builds of Swift-DocC (or other programs that use Swift-Markdown) won't crash, but debug builds will have more information. Does that sound alright?

**Comment by gfinger** [comment]
The expression ^[bla](xyz: 'abc') is a completely legitimate user input and must in no way lead to a crash of the program. If it does, it is a programming error. To check for programming errors assertions could be one means. For example you could check the pre- and post-conditions of a function call using assertions. In the specific case here a simple unit test might be the better solution.

In the article https://www.kodeco.com/29501177-attributedstring-tutorial-for-swift-getting-started expressions like ^[bla](xyz: 'abc') are the way of defining custom attributes in AttributedStrings using Markdown markups. The expression is mapped to a "run" of type paragraph, which contains the information about the custom attribute and its value. Actually my real request, besides avoiding the fatal error, is an appropriate support of this kind of markups for custom attributes in swift-markdown. If someone could give me a hint where to start, I might have a look to add this as a feature.
