### ISSUE TITLE
Add this package dependency failed: © Failed to resolve dependencies Dependencies could not be resolved because root depends...

### ISSUE THREAD

**Issue by mattyoung** [apple/swift-markdown#95]
What's wrong? I just simply added this package dependency to a brand new project.

**Comment by QuietMisdreavus** [comment]
Can you paste the full error in a comment? It looks like the title cut off.

But if i were to guess, i think it's likely to do with the version of ArgumentParser that Swift-Markdown uses. Is your project using that package as well? What version?

**Comment by dylanfrankcom** [comment]
I faced this issue as well as I was using ArgumentParser. The full error gets cut off within Xcode which is why it probably isn't provided. 

I think you are correct though, @QuietMisdreavus. Removing the ArgumentParser package, adding the Swift-Markdown package, and then re-adding ArgumentParser solved this issue on my end. Thanks!

**Comment by taofuns** [comment]
if you use Xcode to add this package, choose **Dependency Rule** to *Branch* and *main*
![image](https://user-images.githubusercontent.com/80188597/231553796-a9ab252a-ea47-4f7a-9790-171807866cf5.jpeg)

**Comment by Kyle-Ye** [comment]
For most developers, it is suggested to use version dependency instead of branch dependency to avoid dependency conflict.

The current releases contains 0.2 which corresponds to Swift release/5.8 and 0.3 which corresponds to Swift release/5.9.

Closed as resolved.
